### ISSUE TITLE
Problems with this

### ISSUE THREAD

**Issue by trd87** [Mikjaer/WioShop#1]
<img width="1139" alt="skjermbilde 2017-03-10 21 58 31" src="https://cloud.githubusercontent.com/assets/26334758/23813029/3ac95d78-05dd-11e7-8476-67fd683c1aba.png">

**Comment by trd87** [comment]
Iam Using: WP Version 4.7.3

**Comment by Mikjaer** [comment]
Dear trd87

Your system needs to abide by the minimal requirement, in this case you are missing the yaml plugin. Ive updated the README file with instructions on how to fix this issue.

If you need further support regarding this matter, we offer paid support and other services through our company: https://www.mikjaer-consulting.dk/kontakt/

**Comment by Mikjaer** [comment]
Hi there
I made a revision with legacy support for antiquated hosting providers ;)

https://github.com/Mikjaer/WioShop/blob/master/zip/WioShop-1.1Beta.zip

If you use it on a webserver without pecl-yaml it will failback and use config.php for configuration, please add you settings inthere.

/ Mikkel
